server.port=8087

# ============ ZIPKIN CONFIGS ================
management.tracing.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
management.tracing.sampling.probability=0.1
management.tracing.propagation.type=b3
management.tracing.instrumentation.http.client.enabled=true
management.tracing.instrumentation.http.server.enabled=true
logging.pattern.level=%5p [%X{traceId:-},%X{spanId:-}]

# ============ Eureka ============
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:8761/eureka/}
