server.port=8761

# ============ Eureka Server ============
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000

# ============ ZIPKIN CONFIGS ================
management.tracing.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
management.tracing.sampling.probability=0.1
management.tracing.propagation.type=b3
logging.pattern.level=%5p [%X{traceId:-},%X{spanId:-}]
