server.port=8081

# ============ DATABASE ================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/userdb
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=public

# ============ KEYCLOAK ADMIN CLIENT ================
keycloak.admin.server-url=${KEYCLOAK_URL:http://keycloak:8080}
keycloak.admin.realm=booking-platform
keycloak.admin.client-id=user-service-admin
keycloak.admin.client-secret=${USER_SERVICE_KEYCLOAK_CLIENT_SECRET}

# ============ ZIPKIN CONFIGS ================
management.tracing.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
management.tracing.sampling.probability=0.1
management.tracing.propagation.type=b3
management.tracing.instrumentation.http.client.enabled=true
management.tracing.instrumentation.http.server.enabled=true
logging.pattern.level=%5p [%X{traceId:-},%X{spanId:-}]

# ============ Eureka ============
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:8761/eureka/}
