apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-service-config
  namespace: booking-platform
data:
  SPRING_PROFILES_ACTIVE: dev
  CONFIG_SERVER_URL: http://config-service:8888
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-service:8761/eureka/
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
