server.port=8083

# ============ ZIPKIN CONFIGS ================
# Turns on distributed tracing in the service.
# If this is false, no spans are created, nothing is sent to Zipkin.
management.tracing.enabled=true
# Defines where spans are sent.
# Zipkin will not receive any data if this is missing or wrong.
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
# Controls how many requests are traced.
management.tracing.sampling.probability=1.0
# Defines how trace IDs are passed between services.
# b3 = Zipkin standard
# Required if you want consistent traces across services
management.tracing.propagation.type=b3
# Traces outgoing HTTP calls (RestTemplate, WebClient, Feign).
management.tracing.instrumentation.http.client.enabled=true
# Traces incoming HTTP requests to your service.
management.tracing.instrumentation.http.server.enabled=true
# Adds traceId & spanId to logs.
logging.pattern.level=%5p [%X{traceId:-},%X{spanId:-}]