apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: booking-platform
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: ${DB_POSTGRES_PASSWORD}
