-- ============================================================================
-- V1: Create bookings table
-- ============================================================================
-- Tracks the full lifecycle of a booking: PENDING → PAYMENT_PROCESSING →
-- CONFIRMED → CANCELLED → REFUND_PENDING → REFUNDED.
--
-- Design notes:
--   - UUID primary key generated by PostgreSQL (gen_random_uuid()) — avoids
--     sequence hotspot under high insert load.
--   - idempotency_key UNIQUE constraint prevents duplicate bookings from retried
--     client requests.
--   - status stored as VARCHAR, not a PostgreSQL enum, so new states can be added
--     without a DDL migration that requires an exclusive lock.
--   - hold_expires_at used by the hold-expiration scheduler (P3-04) to auto-cancel
--     PENDING bookings whose payment was never initiated.
--   - version column powers Hibernate optimistic locking — incremented on every UPDATE.
-- ============================================================================

CREATE TABLE bookings (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             VARCHAR(255)    NOT NULL,
    event_id            VARCHAR(255)    NOT NULL,
    event_title         VARCHAR(500)    NOT NULL,
    status              VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    seat_category       VARCHAR(255)    NOT NULL,
    quantity            INTEGER         NOT NULL CHECK (quantity > 0),
    unit_price          DECIMAL(10, 2)  NOT NULL,
    total_price         DECIMAL(10, 2)  NOT NULL,
    currency            VARCHAR(3)      NOT NULL DEFAULT 'USD',
    idempotency_key     VARCHAR(255)    NOT NULL UNIQUE,
    hold_expires_at     TIMESTAMPTZ     NOT NULL,
    cancellation_reason TEXT,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    version             BIGINT          NOT NULL DEFAULT 0
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Primary access pattern: load a user's booking history
CREATE INDEX idx_bookings_user_id ON bookings (user_id);

-- Used when an event is cancelled to find all affected bookings
CREATE INDEX idx_bookings_event_id ON bookings (event_id);

-- Used for status-filtered queries (e.g. list only CONFIRMED bookings)
CREATE INDEX idx_bookings_status ON bookings (status);

-- Partial index on hold expiry — only PENDING bookings have active holds.
-- The P3-04 scheduler uses this to efficiently find expired holds without
-- scanning the full table.
CREATE INDEX idx_bookings_hold_expires_at ON bookings (hold_expires_at) WHERE status = 'PENDING';
