apiVersion: v1
kind: Secret
metadata:
  name: ticket-service-secret
  namespace: booking-platform
type: Opaque
stringData:
  DB_MONGO_USERNAME: ${DB_MONGO_USERNAME}
  DB_MONGO_PASSWORD: ${DB_MONGO_PASSWORD}
