apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secret
  namespace: booking-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ${DB_POSTGRES_PASSWORD}
  DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
