apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking-platform
spec:
  selector:
    app: booking-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9094
      targetPort: 9094
