package com.booking.platform.payment_service.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a row in the {@code outbox_events} table (P4-04).
 *
 * <p><b>Transactional Outbox Pattern:</b> instead of publishing events directly to Kafka
 * (which can fail after the DB transaction commits), we write the event to this table
 * <em>in the same transaction</em> as the payment status change. A scheduled poller
 * ({@link com.booking.platform.payment_service.messaging.publisher.impl.OutboxPollingPublisher})
 * reads unpublished rows and publishes them to Kafka.
 *
 * <p>Key fields:
 * <ul>
 *   <li>{@link #aggregateType} — the domain aggregate (e.g. "Payment"). Used for filtering.</li>
 *   <li>{@link #aggregateId} — the aggregate's ID (e.g. payment UUID). Used for ordering per-aggregate.</li>
 *   <li>{@link #eventType} — the event name (e.g. "PaymentCompleted", "PaymentFailed").
 *       The poller maps this to a Kafka topic.</li>
 *   <li>{@link #payload} — the full event data as JSON. The poller parses this to build
 *       the Protobuf message before publishing.</li>
 *   <li>{@link #publishedAt} — {@code NULL} means "not yet published". The poller sets this
 *       after a successful Kafka send. The cleanup job deletes rows older than 24 hours.</li>
 * </ul>
 *
 * <p>Flyway owns the schema ({@code V2__create_outbox_events_table.sql}).
 * JPA is configured with {@code ddl-auto=validate}.
 */
@Entity
@Table(name = "outbox_events")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OutboxEventEntity {

    /** UUID primary key, generated by PostgreSQL gen_random_uuid(). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Domain aggregate type, e.g. "Payment". */
    @Column(name = "aggregate_type", nullable = false, length = 100)
    private String aggregateType;

    /** Domain aggregate ID, e.g. the payment UUID as a string. */
    @Column(name = "aggregate_id", nullable = false, length = 100)
    private String aggregateId;

    /** Event type name, e.g. "PaymentCompleted" or "PaymentFailed". */
    @Column(name = "event_type", nullable = false, length = 100)
    private String eventType;

    /**
     * Full event payload as JSON (stored as PostgreSQL JSONB).
     * Contains all fields needed to build the Protobuf message at publish time.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", nullable = false, columnDefinition = "jsonb")
    private String payload;

    /** When this outbox event was created (same instant as the payment state change). */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * When this event was successfully published to Kafka.
     * {@code NULL} means "not yet published" — the poller queries for these rows.
     * After publishing, the poller sets this to {@code Instant.now()}.
     */
    @Column(name = "published_at")
    private Instant publishedAt;
}
