package com.booking.platform.payment_service.entity;

import com.booking.platform.payment_service.constants.BkgConstants.BkgPaymentsConstants;
import com.booking.platform.payment_service.entity.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a payment transaction in the {@code payments} table.
 *
 * <p>Design decisions:
 * <ul>
 *   <li>{@link #id} — UUID primary key, generated by PostgreSQL ({@code gen_random_uuid()}).</li>
 *   <li>{@link #bookingId} — links this payment to the booking it pays for.
 *       Indexed for fast saga lookups (booking-service asks "what payment exists for this booking?").</li>
 *   <li>{@link #externalPaymentId} — Stripe charge/payment-intent ID, set after gateway responds.
 *       Indexed for webhook lookups (Stripe sends callbacks with its own ID, not ours).</li>
 *   <li>{@link #idempotencyKey} — unique constraint prevents duplicate charges from retried Kafka messages.</li>
 *   <li>{@link #version} — optimistic locking prevents concurrent status-update conflicts
 *       (e.g. webhook + polling both trying to mark COMPLETED at the same time).</li>
 * </ul>
 *
 * <p>Flyway owns the schema. JPA is configured with {@code ddl-auto=validate} —
 * it will verify the entity matches the table but will never modify it.
 */
@Entity
@Table(
    name = BkgPaymentsConstants.TABLE_NAME,
    indexes = {
        @Index(name = BkgPaymentsConstants.INDEX_BOOKING_ID, columnList = BkgPaymentsConstants.BOOKING_ID),
        @Index(name = BkgPaymentsConstants.INDEX_USER_ID, columnList = BkgPaymentsConstants.USER_ID),
        @Index(name = BkgPaymentsConstants.INDEX_STATUS, columnList = BkgPaymentsConstants.STATUS),
        @Index(name = BkgPaymentsConstants.INDEX_EXTERNAL_PAYMENT_ID, columnList = BkgPaymentsConstants.EXTERNAL_PAYMENT_ID)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentEntity {

    /** UUID primary key, generated by PostgreSQL gen_random_uuid(). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = BkgPaymentsConstants.ID, updatable = false, nullable = false)
    private UUID id;

    /** UUID of the booking this payment is for. */
    @Column(name = BkgPaymentsConstants.BOOKING_ID, nullable = false)
    private String bookingId;

    /** Keycloak subject (sub claim) of the user who initiated the payment. */
    @Column(name = BkgPaymentsConstants.USER_ID, nullable = false)
    private String userId;

    /** Payment amount. Stored as DECIMAL(10,2). */
    @Column(name = BkgPaymentsConstants.AMOUNT, nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    /** ISO 4217 currency code (e.g. "USD"). */
    @Column(name = BkgPaymentsConstants.CURRENCY, nullable = false, length = 3)
    private String currency;

    /** Current status in the payment lifecycle state machine. */
    @Enumerated(EnumType.STRING)
    @Column(name = BkgPaymentsConstants.STATUS, nullable = false, length = 50)
    private PaymentStatus status;

    /**
     * Payment method identifier (e.g. "card", "bank_transfer").
     * Nullable — set when Stripe integration is wired in (P4-02).
     */
    @Column(name = BkgPaymentsConstants.PAYMENT_METHOD)
    private String paymentMethod;

    /**
     * External payment gateway ID (e.g. Stripe charge ID: "ch_1234...").
     * Nullable — set after the gateway responds.
     * Indexed for webhook lookups where the gateway sends its own ID.
     */
    @Column(name = BkgPaymentsConstants.EXTERNAL_PAYMENT_ID)
    private String externalPaymentId;

    /**
     * Reason for payment failure, if applicable.
     * Nullable — only set when status is {@link PaymentStatus#FAILED}.
     */
    @Column(name = BkgPaymentsConstants.FAILURE_REASON, columnDefinition = BkgPaymentsConstants.FAILURE_REASON_COLUMN_DEFINITION)
    private String failureReason;

    /**
     * Client-generated idempotency key (typically the bookingId or a UUID).
     * The unique constraint ensures that retried Kafka messages don't create
     * duplicate payment records.
     */
    @Column(name = BkgPaymentsConstants.IDEMPOTENCY_KEY, nullable = false, unique = true)
    private String idempotencyKey;

    /** Timestamp when the record was first created. Set once by Hibernate. */
    @CreationTimestamp
    @Column(name = BkgPaymentsConstants.CREATED_AT, nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update. Updated automatically by Hibernate. */
    @UpdateTimestamp
    @Column(name = BkgPaymentsConstants.UPDATED_AT, nullable = false)
    private Instant updatedAt;

    /**
     * Optimistic locking version. Hibernate increments this on every update.
     * Concurrent modifications (e.g. webhook + polling race) will throw
     * {@link jakarta.persistence.OptimisticLockException} instead of silently overwriting.
     */
    @Version
    @Column(name = BkgPaymentsConstants.VERSION, nullable = false)
    private Long version;
}
