package com.booking.platform.booking_service.entity;

import com.booking.platform.booking_service.constants.EntityConst;
import com.booking.platform.booking_service.entity.enums.BookingStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a booking in the {@code bookings} table.
 *
 * <p>Design decisions:
 * <ul>
 *   <li>{@link #id} — UUID primary key, generated by PostgreSQL ({@code gen_random_uuid()}).</li>
 *   <li>{@link #eventTitle} — denormalized from event-service to avoid an extra gRPC call on reads.</li>
 *   <li>{@link #idempotencyKey} — unique constraint prevents duplicate bookings from retried requests.</li>
 *   <li>{@link #holdExpiresAt} — used by the P3-04 scheduler to expire PENDING bookings.</li>
 *   <li>{@link #version} — optimistic locking prevents concurrent status-update conflicts.</li>
 * </ul>
 *
 * <p>Flyway owns the schema. JPA is configured with {@code ddl-auto=validate} —
 * it will verify the entity matches the table but will never modify it.
 */
@Entity
@Table(
    name = EntityConst.Booking.TABLE_NAME,
    indexes = {
        @Index(name = EntityConst.Booking.IDX_USER_ID, columnList = EntityConst.Booking.USER_ID),
        @Index(name = EntityConst.Booking.IDX_EVENT_ID, columnList = EntityConst.Booking.EVENT_ID),
        @Index(name = EntityConst.Booking.IDX_STATUS, columnList = EntityConst.Booking.STATUS)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BookingEntity {

    /** UUID primary key, generated by PostgreSQL gen_random_uuid(). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = EntityConst.Booking.ID, updatable = false, nullable = false)
    private UUID id;

    /** Keycloak subject (sub claim) of the user who made this booking. */
    @Column(name = EntityConst.Booking.USER_ID, nullable = false)
    private String userId;

    /** MongoDB ObjectId of the event from event-service. */
    @Column(name = EntityConst.Booking.EVENT_ID, nullable = false)
    private String eventId;

    /**
     * Event title at the time of booking, denormalized to avoid an extra gRPC call
     * when loading booking history. Stale data is acceptable — titles rarely change
     * after publication, and booking history is a point-in-time record.
     */
    @Column(name = EntityConst.Booking.EVENT_TITLE, nullable = false, length = 500)
    private String eventTitle;

    /** Current status in the booking lifecycle state machine. */
    @Enumerated(EnumType.STRING)
    @Column(name = EntityConst.Booking.STATUS, nullable = false, length = 50)
    private BookingStatus status;

    /** Name of the seat category (e.g. "VIP", "General Admission"). */
    @Column(name = EntityConst.Booking.SEAT_CATEGORY, nullable = false)
    private String seatCategory;

    /** Number of seats reserved. Always ≥ 1. */
    @Column(name = EntityConst.Booking.QUANTITY, nullable = false)
    private int quantity;

    /** Price per seat at the time of booking. Stored as DECIMAL(10,2). */
    @Column(name = EntityConst.Booking.UNIT_PRICE, nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPrice;

    /**
     * Total price = unitPrice × quantity.
     * Stored explicitly to avoid recomputation and to capture any future discount logic.
     */
    @Column(name = EntityConst.Booking.TOTAL_PRICE, nullable = false, precision = 10, scale = 2)
    private BigDecimal totalPrice;

    /** ISO 4217 currency code (e.g. "USD"). */
    @Column(name = EntityConst.Booking.CURRENCY, nullable = false, length = 3)
    private String currency;

    /**
     * Client-generated idempotency key (UUID). The unique constraint ensures that
     * retried requests with the same key return the existing booking instead of
     * creating a duplicate.
     */
    @Column(name = EntityConst.Booking.IDEMPOTENCY_KEY, nullable = false, unique = true)
    private String idempotencyKey;

    /**
     * When the seat hold expires. Used by the P3-04 scheduler to auto-cancel
     * PENDING bookings whose payment was never initiated.
     * Only meaningful while {@link #status} is {@link BookingStatus#PENDING}.
     */
    @Column(name = EntityConst.Booking.HOLD_EXPIRES_AT, nullable = false)
    private Instant holdExpiresAt;

    /** Optional reason provided when cancelling the booking. */
    @Column(name = EntityConst.Booking.CANCELLATION_REASON, columnDefinition = "TEXT")
    private String cancellationReason;

    /** Timestamp when the record was first created. Set once by Hibernate. */
    @CreationTimestamp
    @Column(name = EntityConst.Booking.CREATED_AT_COLUMN, nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update. Updated automatically by Hibernate. */
    @UpdateTimestamp
    @Column(name = EntityConst.Booking.UPDATED_AT, nullable = false)
    private Instant updatedAt;

    /**
     * Optimistic locking version. Hibernate increments this on every update.
     * Concurrent modifications on the same booking row will throw
     * {@link jakarta.persistence.OptimisticLockException} instead of silently overwriting each other.
     */
    @Version
    @Column(name = EntityConst.Booking.VERSION, nullable = false)
    private Long version;
}
