package com.booking.platform.booking_service.entity;

import com.booking.platform.booking_service.constants.EntityConst;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity for a single cart line in the {@code cart_items} table.
 *
 * <p>A cart line is one event + seat category + quantity for a user. It carries a
 * price/title snapshot so the cart can be rendered and checked out without a
 * round-trip; the authoritative amount is still re-derived from event-service at
 * checkout. The {@code (user_id, event_id, seat_category)} unique constraint makes
 * "add to cart" an upsert — the same line is never duplicated, only its quantity updated.
 *
 * <p>Flyway owns the schema; JPA runs with {@code ddl-auto=validate}.
 */
@Entity
@Table(
    name = EntityConst.CartItem.TABLE_NAME,
    indexes = {
        @Index(name = EntityConst.CartItem.IDX_USER_ID, columnList = EntityConst.CartItem.USER_ID)
    },
    uniqueConstraints = {
        @UniqueConstraint(
            name = EntityConst.CartItem.UQ_USER_EVENT_CATEGORY,
            columnNames = {
                EntityConst.CartItem.USER_ID,
                EntityConst.CartItem.EVENT_ID,
                EntityConst.CartItem.SEAT_CATEGORY
            })
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CartItemEntity {

    /** UUID primary key, generated by PostgreSQL gen_random_uuid(). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = EntityConst.CartItem.ID, updatable = false, nullable = false)
    private UUID id;

    /** Keycloak subject (sub claim) of the cart's owner. */
    @Column(name = EntityConst.CartItem.USER_ID, nullable = false)
    private String userId;

    /** MongoDB ObjectId of the event from event-service. */
    @Column(name = EntityConst.CartItem.EVENT_ID, nullable = false)
    private String eventId;

    /** Event title snapshot, so the cart renders without an extra gRPC call. */
    @Column(name = EntityConst.CartItem.EVENT_TITLE, nullable = false, length = 500)
    private String eventTitle;

    /** Name of the seat category (e.g. "VIP", "General Admission"). */
    @Column(name = EntityConst.CartItem.SEAT_CATEGORY, nullable = false)
    private String seatCategory;

    /** Number of seats for this line. Always ≥ 1. */
    @Column(name = EntityConst.CartItem.QUANTITY, nullable = false)
    private int quantity;

    /** Price-per-seat snapshot at the time the line was added. */
    @Column(name = EntityConst.CartItem.UNIT_PRICE, nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPrice;

    /** ISO 4217 currency code (e.g. "USD"). */
    @Column(name = EntityConst.CartItem.CURRENCY, nullable = false, length = 3)
    private String currency;

    /** Timestamp when the line was first added. Set once by Hibernate. */
    @CreationTimestamp
    @Column(name = EntityConst.CartItem.CREATED_AT_COLUMN, nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update (e.g. quantity change). Maintained by Hibernate. */
    @UpdateTimestamp
    @Column(name = EntityConst.CartItem.UPDATED_AT, nullable = false)
    private Instant updatedAt;

    /** Optimistic-locking version — guards concurrent quantity edits on the same line. */
    @Version
    @Column(name = EntityConst.CartItem.VERSION, nullable = false)
    private Long version;
}
