package com.booking.platform.booking_service.entity;

import com.booking.platform.booking_service.constants.EntityConst;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity for a "lovelist" entry in the {@code favorites} table.
 *
 * <p>A favorite is a pure pointer — {@code (user_id, event_id)} — with no denormalized
 * event fields; display data (title, category, city, date, image) is hydrated live from
 * event-service so a favorite never goes stale. The unique constraint makes
 * "add favorite" idempotent. Favorites are insert/delete only, so there is no
 * version column.
 *
 * <p>Flyway owns the schema; JPA runs with {@code ddl-auto=validate}.
 */
@Entity
@Table(
    name = EntityConst.Favorite.TABLE_NAME,
    indexes = {
        @Index(name = EntityConst.Favorite.IDX_USER_ID, columnList = EntityConst.Favorite.USER_ID)
    },
    uniqueConstraints = {
        @UniqueConstraint(
            name = EntityConst.Favorite.UQ_USER_EVENT,
            columnNames = { EntityConst.Favorite.USER_ID, EntityConst.Favorite.EVENT_ID })
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FavoriteEntity {

    /** UUID primary key, generated by PostgreSQL gen_random_uuid(). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = EntityConst.Favorite.ID, updatable = false, nullable = false)
    private UUID id;

    /** Keycloak subject (sub claim) of the lovelist's owner. */
    @Column(name = EntityConst.Favorite.USER_ID, nullable = false)
    private String userId;

    /** MongoDB ObjectId of the favorited event from event-service. */
    @Column(name = EntityConst.Favorite.EVENT_ID, nullable = false)
    private String eventId;

    /** Timestamp when the event was favorited. Set once by Hibernate. */
    @CreationTimestamp
    @Column(name = EntityConst.Favorite.CREATED_AT_COLUMN, nullable = false, updatable = false)
    private Instant createdAt;
}
