apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  namespace: booking-platform
data:
  SPRING_DATA_REDIS_HOST: redis-master
  JWT_ISSUER_URI: http://keycloak/realms/booking-platform
  JWT_JWK_SET_URI: http://keycloak/realms/booking-platform/protocol/openid-connect/certs
  GRPC_CLIENT_USER_SERVICE_ADDRESS: static://user-service:9091
  GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_EVENT_SERVICE_ADDRESS: static://event-service:9093
  GRPC_CLIENT_EVENT_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_BOOKING_SERVICE_ADDRESS: static://booking-service:9094
  GRPC_CLIENT_BOOKING_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_PAYMENT_SERVICE_ADDRESS: static://payment-service:9095
  GRPC_CLIENT_PAYMENT_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_TICKET_SERVICE_ADDRESS: static://ticket-service:9096
  GRPC_CLIENT_TICKET_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_ANALYTICS_SERVICE_ADDRESS: static://analytics-service:9097
  GRPC_CLIENT_ANALYTICS_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
