apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: booking-platform
spec:
  selector:
    app: graphql-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
