-- ============================================================================
-- V1: Create payments table
-- ============================================================================
-- Tracks the full lifecycle of a payment: INITIATED → PROCESSING →
-- COMPLETED / FAILED → REFUND_INITIATED → REFUNDED.
--
-- Design notes:
--   - UUID primary key generated by PostgreSQL (gen_random_uuid()) — avoids
--     sequence hotspot under high insert load.
--   - idempotency_key UNIQUE constraint prevents duplicate charges from retried
--     Kafka messages.
--   - status stored as VARCHAR, not a PostgreSQL enum, so new states can be added
--     without a DDL migration that requires an exclusive lock.
--   - external_payment_id indexed for Stripe webhook lookups (P4-02).
--   - version column powers Hibernate optimistic locking — incremented on every UPDATE.
-- ============================================================================

CREATE TABLE payments (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id              VARCHAR(255)    NOT NULL,
    user_id                 VARCHAR(255)    NOT NULL,
    amount                  DECIMAL(10, 2)  NOT NULL,
    currency                VARCHAR(3)      NOT NULL DEFAULT 'USD',
    status                  VARCHAR(50)     NOT NULL DEFAULT 'INITIATED',
    payment_method          VARCHAR(100),
    external_payment_id     VARCHAR(255),
    failure_reason          TEXT,
    idempotency_key         VARCHAR(255)    NOT NULL UNIQUE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    version                 BIGINT          NOT NULL DEFAULT 0
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Saga lookup: find payment for a booking (booking-service asks "is this booking paid?")
CREATE INDEX idx_payments_booking_id ON payments (booking_id);

-- User-scoped queries: list a user's payment history
CREATE INDEX idx_payments_user_id ON payments (user_id);

-- Status-filtered queries (e.g. find all PROCESSING payments for timeout monitoring)
CREATE INDEX idx_payments_status ON payments (status);

-- Stripe webhook lookup: gateway sends its own charge ID, we need to find our record
CREATE INDEX idx_payments_external_payment_id ON payments (external_payment_id);

-- Partial index on active payments — only INITIATED and PROCESSING payments need
-- timeout monitoring. Avoids scanning completed/failed records.
CREATE INDEX idx_payments_active ON payments (created_at) WHERE status IN ('INITIATED', 'PROCESSING');
