apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: booking-platform
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_MAIL_HOST: mailhog
  GRPC_CLIENT_USER_SERVICE_ADDRESS: static://user-service:9091
  GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  GRPC_CLIENT_BOOKING_SERVICE_ADDRESS: static://booking-service:9094
  GRPC_CLIENT_BOOKING_SERVICE_NEGOTIATION_TYPE: PLAINTEXT
  KEYCLOAK_SERVICE_TOKEN_URL: http://keycloak/realms/booking-platform/protocol/openid-connect/token
