apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: booking-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: booking-platform/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8086
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
