apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: booking-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ${DB_POSTGRES_PASSWORD}
  DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
  USER_SERVICE_KEYCLOAK_CLIENT_SECRET: ${USER_SERVICE_KEYCLOAK_CLIENT_SECRET}
